* Update to pre-release version for 0.0.3

diff --git a/deps/getDeps b/deps/getDeps
--- a/deps/getDeps
+++ b/deps/getDeps
@@ -21,11 +21,11 @@
 PNG_DIR="/usr/local"
 
 #Dependency ID, URL and name
-DEPIDS=( 0 1 2 3 4 5 )
-DEPNAMES=( libpng freetype ftgl wxwidgets mathgl dylibbundler)
-DEPURLS=(http://downloads.sourceforge.net/project/libpng/01-libpng-master/1.4.3/libpng-1.4.3.tar.gz http://downloads.sourceforge.net/project/freetype/freetype2/2.4.1/freetype-2.4.1.tar.gz http://downloads.sourceforge.net/project/ftgl/FTGL%20Source/2.1.3%7Erc5/ftgl-2.1.3-rc5.tar.gz http://downloads.sourceforge.net/project/wxwindows/2.8.11/wxWidgets-2.8.11.tar.gz http://downloads.sourceforge.net/project/mathgl/mathgl/mathgl%201.10.2.1/mathgl-1.10.2.1.tgz http://downloads.sourceforge.net/project/macdylibbundler/macdylibbundler/0.3.1/dylibbundler0.3.1.zip)
-DEPFILENAMES=(libpng-1.4.3.tar.gz freetype-2.4.1.tar.gz ftgl-2.1.3-rc5.tar.gz  wxWidgets-2.8.11.tar.gz mathgl-1.10.2.1.tgz dylibbundler0.3.1.zip)
-DEPMDSUM=(df3521f61a1b8b69489d297c0ca8c1f8 2c4f33ee9242be7ec5e876952ae99755 fcf4d0567b7de9875d4e99a9f7423633 ce80389e1b70d6a518c80b7b715b763e 4122428797fd0c25a096c377b9ffe44a 8feedad7224e6b928a9c65dc939a48bb)
+DEPIDS=( 0 1 2 3 4 5 6)
+DEPNAMES=( libpng freetype ftgl wxwidgets mathgl dylibbundler qhull)
+DEPURLS=(http://downloads.sourceforge.net/project/libpng/01-libpng-master/1.4.3/libpng-1.4.3.tar.gz http://downloads.sourceforge.net/project/freetype/freetype2/2.4.1/freetype-2.4.1.tar.gz http://downloads.sourceforge.net/project/ftgl/FTGL%20Source/2.1.3%7Erc5/ftgl-2.1.3-rc5.tar.gz http://downloads.sourceforge.net/project/wxwindows/2.8.11/wxWidgets-2.8.11.tar.gz http://downloads.sourceforge.net/project/mathgl/mathgl/mathgl%201.10.2.1/mathgl-1.10.2.1.tgz http://downloads.sourceforge.net/project/macdylibbundler/macdylibbundler/0.3.1/dylibbundler0.3.1.zip http://www.qhull.org/download/qhull-2010.1-src.tgz)
+DEPFILENAMES=(libpng-1.4.3.tar.gz freetype-2.4.1.tar.gz ftgl-2.1.3-rc5.tar.gz  wxWidgets-2.8.11.tar.gz mathgl-1.10.2.1.tgz dylibbundler0.3.1.zip qhull-2010.1-src.tgz)
+DEPMDSUM=(df3521f61a1b8b69489d297c0ca8c1f8 2c4f33ee9242be7ec5e876952ae99755 fcf4d0567b7de9875d4e99a9f7423633 ce80389e1b70d6a518c80b7b715b763e 4122428797fd0c25a096c377b9ffe44a 8feedad7224e6b928a9c65dc939a48bb e64138470acdeb18f752a0bc2a11ceb4)
 
 OS_NAME=`uname`
 
@@ -108,7 +108,7 @@ echo "int main(int argc, char *argv[]) { return 0; } ; " > gcctest.c
 gcc gcctest.c -o gcctest
 
 if [ ! -f gcctest ] ; then
-	echo "You do not have gcc (C compiler) installed?? Install it into your PATH, then try again."
+	echo "You do not have gcc (GNU compiler frontend) installed?? Install it into your PATH, then try again."
 	exit 1
 fi
 rm gcctest.c gcctest
@@ -490,7 +490,24 @@ do
 			esac
 
 			;;
+		qhull)
+			if [ x`which cmake` == "" ] ; then
+				echo "Cmake not found on your system. This is needed to build qhull (sigh.). You can install it from http://www.cmake.org/cmake/resources/software.html"
+			else
+				#build
+				cmake .
+				make
 
+				#OK, lets install!
+				echo "I want to install ${DEPNAMES[$i]} to the system:"
+				sudo make install
+				if [ $? -ne 0 ] ; then
+					echo "Damn. unable to install. aborting"
+					exit 1
+				fi
+			fi
+			
+			;;
 		*)
 			echo "There is a bug in the script. I do not know the dependency ${DEPNAMES[$i]}. Aborting"
 			exit 1
